spring.application.name=ERPilot




spring.main.web-application-type=servlet
# 1. Connexion PostgreSQL (Ajuste le nom de ta BDD, user et password)
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_demo
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Remplace ollama.base-url et ollama.model.embedding par :
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text