spring.application.name=ERPilot
spring.main.web-application-type=servlet


spring.datasource.url=jdbc:postgresql://localhost:5432/erp_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


erpilot.connection.url=jdbc:postgresql://localhost:5432/erp_demo
erpilot.connection.username=postgres
erpilot.connection.password=postgres
erpilot.connection.dialect-name=postgresql
erpilot.connection.max-pool-size=5


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.options.model=llama3.1
spring.ai.ollama.chat.options.temperature=0.1